import {
    Column,
    CreateDateColumn,
    Entity,
    Index,
    PrimaryGeneratedColumn,
    UpdateDateColumn,
} from 'typeorm';

export type AbandonedCartStatus =
    | 'abandoned'   // detected — no checkout in the abandonment window
    | 'recovered'   // manually or automatically flagged as recovered by ops
    | 'converted'   // the visitor later placed an order — auto-set by the scanner
    | 'expired'     // recovery token past its expiry
    | 'dismissed';  // ops marked "don't chase"

/**
 * One row per abandoned cart, keyed on the visitor session that produced
 * it. Rebuilt fresh from `cart_snapshot` events by the periodic scanner,
 * so a session can be updated in-place until it either converts (order
 * placed) or expires (recovery window elapses without any action).
 */
@Entity('abandoned_cart')
@Index('abandoned_cart_session_uniq', ['sessionId'], { unique: true })
@Index('abandoned_cart_visitor_idx', ['visitorId', 'abandonedAt'])
@Index('abandoned_cart_status_idx', ['status', 'abandonedAt'])
@Index('abandoned_cart_email_idx', ['emailHash'])
@Index('abandoned_cart_customer_idx', ['customerId'])
export class AbandonedCart {
    @PrimaryGeneratedColumn()
    id!: number;

    @Column({ length: 64 })
    visitorId!: string;

    @Column({ length: 64 })
    sessionId!: string;

    /** Set when the visitor is signed in. Guest carts stay NULL and are
     *  matched to a customer only if they later sign in (via the same
     *  visitorId) or check out with a linkable email. */
    @Column({ type: 'int', nullable: true })
    customerId!: number | null;

    @Column({ type: 'int', default: 1 })
    channelId!: number;

    @Column({ length: 3 })
    currency!: string;

    /** Total value in the smallest currency unit (pence/cents). Storing
     *  minor units avoids float drift and matches Vendure's convention. */
    @Column({ type: 'int' })
    totalMinor!: number;

    @Column({ type: 'int' })
    itemCount!: number;

    /** JSON array of cart items:
     *  [{ variantId, name, qty, unitPriceMinor, productId?, sku? }, …]
     *  Held as text because the recovery link needs to reconstruct the
     *  cart exactly — we don't want to join back to a live catalog that
     *  may have changed price by the time recovery is attempted. */
    @Column({ type: 'text' })
    itemsJson!: string;

    /** Plain email if the storefront passed one (checkout step 1 usually
     *  captures this). NULL for cold browsers. */
    @Column({ type: 'varchar', length: 255, nullable: true })
    email!: string | null;

    /** SHA-256 of the lowercased email — safe to keep even under
     *  aggressive privacy defaults, and used to link recurring sessions
     *  from the same buyer without exposing the raw address. */
    @Column({ type: 'varchar', length: 64, nullable: true })
    emailHash!: string | null;

    @Column({ type: 'datetime', precision: 3 })
    firstSnapshotAt!: Date;

    @Column({ type: 'datetime', precision: 3 })
    lastSnapshotAt!: Date;

    /** Moment the scanner promoted the session from "active" to
     *  "abandoned" — i.e. no checkout_completed and no fresh
     *  cart_snapshot within the abandonment window. */
    @Column({ type: 'datetime', precision: 3 })
    abandonedAt!: Date;

    @Column({ type: 'datetime', precision: 3, nullable: true })
    recoveredAt!: Date | null;

    /** Signed opaque token that recovers the cart on the storefront.
     *  Regenerated by the admin/recover endpoint; time-bounded. */
    @Column({ type: 'varchar', length: 128, nullable: true, unique: true })
    recoveryToken!: string | null;

    @Column({ type: 'datetime', precision: 3, nullable: true })
    recoveryTokenExpiresAt!: Date | null;

    @Column({ type: 'varchar', length: 32, default: 'abandoned' })
    status!: AbandonedCartStatus;

    @Column({ type: 'int', nullable: true })
    recoveryOrderId!: number | null;

    @Column({ type: 'varchar', length: 2048, nullable: true })
    lastKnownUrl!: string | null;

    @Column({ type: 'varchar', length: 2048, nullable: true })
    lastKnownReferrer!: string | null;

    @Column({ type: 'varchar', length: 100, nullable: true })
    utmSource!: string | null;

    @Column({ type: 'varchar', length: 100, nullable: true })
    utmMedium!: string | null;

    @Column({ type: 'varchar', length: 200, nullable: true })
    utmCampaign!: string | null;

    @Column({ type: 'varchar', length: 16, nullable: true })
    countryCode!: string | null;

    /** True once we've fired the Slack / email notification for this
     *  abandonment. Prevents duplicate notifications when the scanner
     *  re-runs. */
    @Column({ type: 'boolean', default: false })
    notificationSent!: boolean;

    @CreateDateColumn({ precision: 3 })
    createdAt!: Date;

    @UpdateDateColumn({ precision: 3 })
    updatedAt!: Date;
}
